package(default_visibility = ["//third_party/transparent_release:__subpackages__"])

licenses(["notice"])

exports_files([
    "9951f53ca22d9abdbbd664880586c4e2053087a5de891572458e84752ce1a8c1.json",
])
