name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Install mcpp #mcpp is a dependency of Souffle
        run: sudo apt-get install -y mcpp

      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...
      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test --test_output=streamed //...

  check-license-lines:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6

  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Run golint
        run: |
          sudo apt-get install -y golint
          ./scripts/linting.sh
