name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '=1.18.4'

      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test ./...

  # TODO(#113): Find a better, and easier-to-navigate way to report coverage.
  # Generate coverage report for ./pkg/... and ./internal/... and upload the report as an html file.
  # See `go help testflag` and `go tool cover -help` for more options.
  test-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '=1.18.4'
      - name: Run go test
        run: |
          go test -coverpkg=./... -coverprofile coverage.out ./pkg/... ./internal/...
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o coverage.html
      - uses: actions/upload-artifact@v3
        with:
          name: coverage.html
          path: coverage.html

  check-license-lines:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6

  formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '=1.18.4'
      - name: Run go fmt
        run: |
          ./scripts/formatting.sh

  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '=1.18.4'
      - name: Run golint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.48.0
          ./scripts/linting.sh

  vetting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '=1.18.4'
      - name: Run go vet
        run: |
          go vet ./...
